import 'dart:convert';

import 'package:weather_app/models/weather-current_model.dart';
import 'package:weather_app/models/weather-daily_model.dart';
import 'package:weather_app/models/weather-hourly_model.dart';
import 'package:weather_app/models/weather_model.dart';
import 'package:http/http.dart' as http;

class ApiService {
  String apiKey = '2c8848a279b83b708bd1998475800a02';
  String searchUrl = 'https://api.openweathermap.org/data/2.5';
  String baseUrl(lat, lon) {
    String url =
        'https://api.openweathermap.org/data/3.0/onecall?lat=$lat&lon=$lon&appid=$apiKey&units=metric&exclude=minutely';
    return url;
  }

  // Retrieve weather data from the API based on the given latitude (lat) and longitude (lon) coordinates
  Future<WeatherModel> getWeather(lat, lon) async {
    try {
      // The function sends an HTTP GET request to the URL generated by the baseUrl(lat, lon) function.
      final response = await http.get(
        Uri.parse(baseUrl(lat, lon)),
      );
      // Responses received from the API in JSON format are parsed into Dart objects using jsonDecode.
      var jsonString = jsonDecode(response.body);

      // The parsed JSON data is then used to create a WeatherModel object
      WeatherModel weather = WeatherModel(
        current: WeatherCurrentModel(current: jsonString),
        hourly: WeatherHourlyModel(hourly: jsonString),
        daily: WeatherDailyModel(daily: jsonString),
      );

      return weather;
    } catch (e) {
      throw Exception(e);
    }
  }
}
